### PR TITLE
feature/update-dependencies

### PR DESCRIPTION
**Pull request by gavin-brown**

### CODE REVIEW

**Comment by gavin-brown** [comment]
@builtbywill The dependency updates here are pretty minor. Let me know if I should put up a built-branch for testing in studiokit-caliper-js. The tests pass, except for 2 from a mismatch with fixtures. I felt like modifying the tests to match fixtures or modifying the fixtures would start to be a rabbit hole, so I left it

**Comment by gavin-brown** [comment]
@purdue-tlt/full-timers Ready for review

**Review by lily514 — APPROVED** [review]
@gavin-brown I know very little about caliper-js but this looks fine. :thumps:

**Comment by builtbywill** [comment]
@gavin-brown did you just match the package versions with what we use in variate/circuit?

**Review by builtbywill — APPROVED** [review]

**Comment by gavin-brown** [comment]
@builtbywill When possible, I tried to match the packages with the ones in Circuit/Variate such as with lodash and moment. For any other ones that I updated, I tried to update to the newest minor version, but not change major versions

**Pull request merged**
